kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cloud05
nodes:
  - role: control-plane
    extraPortMappings:
      # NodePort 30080 -> Localhost 8080 (Demo Application Service)
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # NodePort 30090 -> Localhost 9090 (Prometheus Dashboard)
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
      # NodePort 30092 -> Localhost 8085 (Argo CD Web UI)
      - containerPort: 30092
        hostPort: 8085
        protocol: TCP
      # NodePort 30095 -> Localhost 3100 (Argo Rollouts Dashboard)
      - containerPort: 30095
        hostPort: 3100
        protocol: TCP
