apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud05-progressive-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git://local-git-server.cloud05.svc.cluster.local:9418/cloud05-gitops.git
    targetRevision: main
    path: gitops/rollout
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud05
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
